#---------------------------------------------------------------------
# GitHub Action Workflow to Deploy
#
# Version      Date        Info
# 1.0          2022        Initial Version
#
# Made by Alex Sanders Webcomplete.io Copyleft (c) 2022
#---------------------------------------------------------------------
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1

    - name: Deploy
      env:
        dest: 'u436523386@145.14.153.243:/home/u436523386/domains/webcomplete.io/public_html/ssh/wp-content/themes/mytheme'
      run: |
        echo "${{secrets.key}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chav --delete \
          -e 'ssh -p 65002 -i ./deploy_key -o StrictHostKeyChecking=no' \
          --archive --compress --delete \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /node_modules/ \
          ./ ${{env.dest}}