name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

- name: Sync
    env:
      dest: 'u436523386@145.14.153.243:/home/u436523386/domains/webcomplete.io/public_html/ssh/wp-content/themes/mytheme'
    run: |
      set -eu
      mkdir "$HOME/.ssh"
      echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      chmod 600 "$HOME/.ssh/key"
      rsync -chav --delete \
        -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
        --exclude /.git/ \
        --exclude /.github/ \
        --exclude /node_modules/ \
        ./ ${{env.dest}}